# Generated by Django 5.0.6 on 2024-09-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldata',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
